import os
os.system("yum -y install epel-release")
os.system("yum -y group install 'Development Tools'")
os.system("yum -y install collectd collectd-write_kafka python-pip ipmitool lm_sensors sysstat wget nano")
os.system("pip install collectd")
os.system("sensors-detect --auto")
os.system("mkdir /root/rapl-read")
os.system("cd /root/rapl-read")
os.system("wget https://raw.githubusercontent.com/deater/uarch-configure/master/rapl-read/Makefile")
os.system("wget https://raw.githubusercontent.com/deater/uarch-configure/master/rapl-read/rapl-plot.c")
os.system("wget https://raw.githubusercontent.com/deater/uarch-configure/master/rapl-read/rapl-read.c")
os.system("wget https://raw.githubusercontent.com/deater/uarch-configure/master/rapl-read/README")
os.system("make")
os.system("cd /root")
os.system("wget https://raw.githubusercontent.com/cristinalunaj/CYBEROPS_config/master/parser.py")#os.system("wget https://raw.githubusercontent.com/spmorillo/Cargas/master/parser.py")
os.system("wget https://raw.githubusercontent.com/cristinalunaj/CYBEROPS_config/master/collectd.conf")#os.system("wget https://raw.githubusercontent.com/spmorillo/Cargas/master/collectd.conf")
os.system("yes | cp -rf /root/collectd.conf /etc/collectd.conf")
os.system("wget https://raw.githubusercontent.com/cristinalunaj/CYBEROPS_config/master/types.db")
os.system("yes | cp -rf /root/types.db /usr/share/collectd/types.db")
os.system("rm -rf types.db collectd.conf")
os.system("systemctl start collectd")